name: jasoneverett
favicon: null
layout_spectrum: 0.45438227569684386
typography_spectrum: 0.6031856457702816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4591738795861602
  lightness: 0.9556273706257343
  saturation: 0.8139762801583856
  rhythmicContrast: 0.04903711099177599
purpose: []
